Feat: Waste management contract
Green-Cycle-Plus/Smart-Contract-V1 pull request #2
Opened 2024-11-12 17:39 UTC by kingAkande

2024-11-12 21:04 UTC, Guzbyte-tech commented on contracts/Wastemanagement.sol
> +    function getUser(address _userAddress) external view returns ( uint256 id,address userAddress,  string memory location, uint256 rating, bool isRegistered ){
A public mapping of address to users can be used to get the user and then this function can be discarded.

2024-11-12 21:10 UTC, Guzbyte-tech commented on contracts/Wastemanagement.sol
> +    function createUser( address _userAddress, string memory _location, uint256 _ratings ) external {
I think the string used for location will consume so much gas if the location is long enough, You can decide to save the longitude and Latutude instead, Also rating when creating a user is not neccessary.

2024-11-14 14:20 UTC, michojekunle requested changes
Please check through the comments for the review

@LayintonDev @Guzbyte-tech @Favvie Please also look through this Pull Request

2024-11-14 14:20 UTC, michojekunle commented on contracts/Wastemanagement.sol
> +
We can have this as uint256 _id = ++numberOfUsers;

instead to save gas and avoid repitition

2024-11-14 14:20 UTC, michojekunle commented on contracts/Wastemanagement.sol
> +    function setUserLocation(int32 latitude, int32 longitude) external {
@Guzbyte-tech @LayintonDev Please check do we need this function for the user to set coordinates

2024-11-14 14:20 UTC, michojekunle commented on contracts/Wastemanagement.sol
> +    // }
@kingAkande we can remove this function completely

2024-11-14 14:20 UTC, michojekunle commented on contracts/libraries/Wastelibrary.sol
- I think for this library some functionalities can be abstracted into this library from the contract above 
- We can have more descriptive and distinct error names

2024-11-14 14:20 UTC, michojekunle commented on contracts/Wastemanagement.sol
> +
I think we can abstract this and only allow recyclers manage confirmation and pickup of waste waste

2024-11-15 07:28 UTC, kingAkande commented on contracts/Wastemanagement.sol
> +    function setUserLocation(int32 latitude, int32 longitude) external {
The thing is, on the frontend we can use the browser's geolocation feature to automatically detect their latitude and longitude. The frontend would handle gathering and formatting the coordinates, then pass them to the contract function. so the contract then saves the latitude and longitude in the contract's storage under the user's profile.   the user would interact with the frontend, but they might not even know they're calling setUserLocation in the smart contract.

2024-11-16 18:30 UTC, merged